spring.application.name=pos-venta-service
spring.datasource.url=jdbc:postgresql://localhost:5433/pos_inventory
spring.datasource.username=servicepos
spring.datasource.password=admin123
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.maximum-pool-size=5

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

# Nombre del microservicio: /pos-venta-service
server.servlet.context-path=/pos-venta-service
# Server port static=8082; server.port = 0 (dynamic)
server.port=8081